# Generated by Django 4.2.4 on 2023-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zipcode', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
