# Generated by Django 4.2.5 on 2023-10-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(default="Prospect Park", max_length=200),
                ),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("zipcode", models.IntegerField(default=0)),
                ("address", models.CharField(default="Prospect Road", max_length=400)),
                (
                    "url",
                    models.CharField(default="https://example.com", max_length=400),
                ),
                ("category", models.CharField(default="park", max_length=100)),
            ],
        ),
    ]
