# Generated by Django 4.2.5 on 2023-10-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='Prospect Road', max_length=400),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(default='park', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='Prospect Park', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='location',
            name='url',
            field=models.CharField(default='https://example.com', max_length=400),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
