# Generated by Django 4.2.5 on 2023-10-11 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("location", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("capacity", models.IntegerField()),
                (
                    "event_location",
                    models.ForeignKey(
                        default=261,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.location",
                    ),
                ),
            ],
        ),
    ]
