# Generated by Django 4.2.5 on 2023-10-11 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_address_alter_location_category_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.ForeignKey(default=261, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
