# Generated by Django 4.2.6 on 2023-11-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventjoin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventjoin",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("withdrawn", "Withdrawn"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("removed", "Removed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
