# Generated by Django 4.2.5 on 2023-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_eventjoin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
