# Generated by Django 4.2.5 on 2023-11-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("events", "0003_alter_eventjoin_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="tags.tag"
            ),
        ),
    ]
