# Generated by Django 4.2.5 on 2023-11-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("events", "0004_event_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(to="tags.tag"),
        ),
    ]
