# Generated by Django 4.2.6 on 2023-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
