# Generated by Django 4.2.6 on 2023-11-14 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_description"),
        ("events", "0006_alter_comment_is_active"),
    ]

    operations = []
