# Generated by Django 4.2.5 on 2023-11-15 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_event_tags_event_tags"),
        ("events", "0007_merge_20231114_1803"),
    ]

    operations = []
