# Generated by Django 4.2.6 on 2023-11-20 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_reaction"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=set(),
        ),
    ]
