# Generated by Django 4.2.5 on 2023-12-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
