# Generated by Django 4.2.5 on 2023-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_notification_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.IntegerField(default=0),
        ),
    ]
